config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :students do
    resources :addresses
  end
end

app/models/address.rb
class Address < ApplicationRecord
  validates_presence_of(:description, :street, :city, :state, :zip_code)
  belongs_to :student
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  validates_presence_of(:title)
  has_many :students
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  validates_presence_of(:student_id, :course_id)
  belongs_to :student
  belongs_to :course
end

app/models/student.rb
class Student < ApplicationRecord
  validates_presence_of :name
  has_many :addresses
  has_many :courses
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController

  def new
    @student = Student.find(params[:student_id])
    @address = Address.new
  end

  def create
    @student = Student.find(params[:student_id])
    @address = @student.addresses.new(address_params)
    if @address.save
      flash[:success] = "You created address #{@address.description} for #{@student.name}"
      redirect_to student_path(@student)
    else
      render :new
    end
  end

  private

  def address_params
    params.require(:address).permit(:description, :street, :city, :state, :zip_code, :student_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      flash[:success] = "You created #{@student.name}"
      redirect_to student_path(@student)
    else
      render :new
    end
  end

  def show
    @student = Student.find(params[:id])
    @addresses = @student.addresses
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])
    @student.update(student_params)
    if @student.save
      flash[:success] = "You updated #{@student.name}"
      redirect_to student_path(@student)
    else
      render :edit
    end
  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy
    redirect_to students_path
  end

  private

  def student_params
    params.require(:student).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/addresses/_nav_bar.html.erb
<nav id="Nav-Bar">
  <p><%= link_to "Students", students_path %></p>
  <p><%= link_to "New Student", new_student_path %></p>
</nav>

app/views/addresses/new.html.erb
<%= render partial: "nav_bar" %>

<%= form_for [@student, @address] do |f| %>
  <p><%= f.label :description %></p>
  <p><%= f.text_field :description %></p>

  <p><%= f.label :street %></p>
  <p><%= f.text_field :street %></p>

  <p><%= f.label :city %></p>
  <p><%= f.text_field :city %></p>

  <p><%= f.label :state %></p>
  <p><%= f.text_field :state %></p>

  <p><%= f.label :zip_code %></p>
  <p><%= f.text_field :zip_code %></p>

  <p><%= f.submit "Add Address" %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TimedExercise</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/edit.html.erb
<%= render partial: "nav_bar" %>

<%= form_for @student do |f| %>
  <p><%= f.label :name %></p>
  <p><%= f.text_field :name %></p>

  <p><%= f.submit "Create" %></p>
<% end %>

app/views/students/index.html.erb
<%= render partial: "nav_bar" %>

<% @students.each do |student| %>
  <section id=<%="student-#{student.id}"%>>
    <p><%= link_to student.name, student_path(student) %></p>
    <%= button_to "Delete", student_path(student.id), method: :delete %>
  </section>
<% end %>

app/views/students/new.html.erb
<%= render partial: "nav_bar" %>

<%= form_for @student do |f| %>
  <p><%= f.label :name %></p>
  <p><%= f.text_field :name %></p>

  <p><%= f.submit "Create" %></p>
<% end %>

app/views/students/show.html.erb
<%= render partial: "nav_bar" %>

<%= @student.name %>

<% @addresses.each do |address| %>
  <p><%= address.description %></p>
  <p><%= address.street %></p>
  <p><%= address.city %></p>
  <p><%= address.state %></p>
  <p><%= address.zip_code %></p>
<%end%>